### ISSUE TITLE
pinkamena1212 access to private repo

### ISSUE THREAD

**Issue by yonguelink** [yonguelink/SchoolWork#2]
> Hey,
> 
> I hope you're doing well! I wanted to reach out and introduce myself. I'm Alison, and I'm currently a student at CEGEP, wrapping up my technical program in computer science. I'm eager to continue my journey in the field by pursuing a computer science degree at the university level.
> 
> As I've been exploring various university programs, I stumbled upon your GitHub profile, where I noticed you've shared some  interesting projects related to your computer science studies. I have to say, I'm quite intrigued by what I've seen so far!
> 
> I'm reaching out today to ask if it would be possible for me to gain access to your GitHub projects. My main goal is to get a better understanding of the kinds of projects and skills that university-level computer science programs delve into. I want to make it clear that I'm not looking to copy your work or use it without permission in any way if I decide to pursue the same university program that you did.
> 
> If you'd be open to granting me access, it would be a tremendous help in making an informed decision about which university program to pursue. Of course, I'd be more than willing to respect any privacy or confidentiality settings you have in place for your GitHub account. If needed, I can even sign any agreements you prefer to ensure the security of your data.
> 
> I appreciate your time and consideration in this matter. Thanks for potentially offering me insights into the world of computer science at the university level.
> 
> Cheers,
> 
> Alison

_Originally posted by @pinkamena1212 in https://github.com/yonguelink/SchoolWork/issues/1#issuecomment-1730449851_

**Comment by yonguelink** [comment]
Hey @pinkamena1212, 

Note that I "moved" your comment to a new issue to avoid spamming the PR's author.

Before I give you access (I totally don't mind you looking into it by curiosity, and I will trust you to **NOT** use it if you ever go into the same program and it turns out they still haven't changed the projects) I have one question:

How did you sttumble upon my profile & this repo?

**Comment by pinkamena1212** [comment]
Thank you for your prompt response. I've been conducting research on GitHub to gather information about the courses that are typically part of computer science programs at various universities. I wasn't able to determine which university you attended, but I noticed that several of the courses in your repository appear to be part of the curriculum I'm interested in pursuing.

**Comment by yonguelink** [comment]
Alright, good luck in your studies! I'll be giving you access in a few minutes. I'm counting on you to **never** share the code that's in there without my approval first & to not use my work to submit any of your homeworks ;)

btw, I went to University of Sherbrooke.
